In [1]:
import numpy as np

In [6]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])

B = np.array([[4,-2,1],[0,3,7],[0,0,2]])

filas_a = A.shape[0]
columnas_a = A.shape[1]

filas_b = B.shape[0]
columnas_b = B.shape[1]

In [7]:
def multiplicacion(A,B,filas_a,columnas_a,filas_b,columnas_b):
    
    respuesta = None
    
    if columnas_a != filas_b:
        
        respuesta = "Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b"
        
    else:
        
        matrizr = np.zeros((filas_a,columnas_b))
        
        for fila in range(filas_b):
            
            f = A[fila,:]
            
            for columna in range(columnas_a):
                
                c = B[:,columna]
                
                valor = np.dot(f,c)
                
                matrizr[fila,columna] = valor
                
                respuesta = matrizr
        
    return respuesta

In [9]:
respuesta = multiplicacion(A,B,filas_a,columnas_a,filas_b,columnas_b)

In [13]:
print("El resultado de la multiplicación de las matrices A y B es: ")
print(respuesta)

El resultado de la multiplicación de las matrices A y B es: 
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
