In [114]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [115]:
G1=(lambda x,y: np.log((x**2)+(y**2)) - np.sin(x*y) - (np.log(2)) -np.log(np.pi), \
   lambda x,y: np.exp(x-y)+ np.cos(x*y))

In [116]:
G2=(lambda x,y,z: 6*x - 2*np.cos(y*z)-1, \
   lambda x,y,z: 9*y + np.sqrt((x**2)+np.sin(z)+1.06)+0.9,\
   lambda x,y,z: 60*z + (3*np.exp(-x*y)) + 10 * np.pi -3)

In [117]:
"Newton Rhapson"

'Newton Rhapson'

In [118]:
"Descenso del gradiente"

'Descenso del gradiente'

In [119]:
def GetF1(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1])
        
    return v

In [120]:
GetF1(G1,np.array([0.,0.]))

C:\Users\jessi\AppData\Local\Temp\ipykernel_14148\705331063.py:1: RuntimeWarning: divide by zero encountered in log
  G1=(lambda x,y: np.log((x**2)+(y**2)) - np.sin(x*y) - (np.log(2)) -np.log(np.pi), \


array([-inf,   2.])

In [121]:
def GetF2(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1],r[2])   
    return v

In [122]:
GetF2(G2,np.array([0.,0.,0.]))

array([-3.        ,  1.92956301, 31.41592654])

In [123]:
def Metric1(G,r):
    return 0.5*np.linalg.norm(GetF1(G,r))**2

In [124]:
def Metric2(G,r):
    return 0.5*np.linalg.norm(GetF2(G,r))**2

In [125]:
def GetJacobian1(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1]) - f[i](rb[0],rb[1]))/(2*h)
            
    
    return J

In [126]:
GetJacobian1(G1,np.array([0.,0.]))

array([[ 0.,  0.],
       [ 1., -1.]])

In [127]:
def GetJacobian2(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2])  )/(2*h)
            
    
    return J

In [128]:
GetJacobian2(G2,np.array([0.,0.,0.]))

array([[ 6.        ,  0.        ,  0.        ],
       [ 0.        ,  9.        ,  0.48564293],
       [ 0.        ,  0.        , 60.        ]])

In [129]:
def GetFig(R,M,it):
    
    fig = plt.figure(figsize=(6,3))
    
    ax = fig.add_subplot(1,2,1)
    ax1 = fig.add_subplot(1,2,2)
    
    ax.plot(R[:it])
    
    ax1.plot(M[:it])
   
    plt.show()

In [130]:
def Minimizer1(G,r,lr=1e-2,epochs=int(1e4),error=1e-7):
    
    metric = 1
    it = 0
    
    M = np.array([])
    R = np.array([r])
    
    while metric > error and it < epochs:
        
        M = np.append(M,Metric1(G,r))
        
        J = GetJacobian1(G,r)
        Vector = GetF1(G,r)
        
        # Machine learning
        r -= lr*np.dot(J,Vector)
        
        R = np.vstack((R,r))
        
        metric = Metric1(G,r)
        
        it += 1
        
        if it%50 == 0:
            clear_output(wait=True)
            GetFig(R,M,it)
            print(r)
            time.sleep(0.001)
    
    return r

In [131]:
x1sol2 = Minimizer1(G1,np.array([0.,0.]))

C:\Users\jessi\AppData\Local\Temp\ipykernel_14148\705331063.py:1: RuntimeWarning: divide by zero encountered in log
  G1=(lambda x,y: np.log((x**2)+(y**2)) - np.sin(x*y) - (np.log(2)) -np.log(np.pi), \


In [132]:
x1sol2

array([nan, inf])

In [133]:
def Minimizer2(G,r,lr=1e-2,epochs=int(1e4),error=1e-7):
    
    metric = 1
    it = 0
    
    M = np.array([])
    R = np.array([r])
    
    while metric > error and it < epochs:
        
        M = np.append(M,Metric2(G,r))
        
        J = GetJacobian2(G,r)
        Vector = GetF2(G,r)
        
        # Machine learning
        r -= lr*np.dot(J,Vector)
        
        R = np.vstack((R,r))
        
        metric = Metric2(G,r)
        
        it += 1
        
        if it%50 == 0:
            clear_output(wait=True)
            GetFig(R,M,it)
            print(r)
            time.sleep(0.001)
    
    return r

In [134]:
x2sol2= Minimizer2(G2,np.array([0.,0.,0.]))

C:\Users\jessi\AppData\Local\Temp\ipykernel_14148\455078042.py:3: RuntimeWarning: overflow encountered in exp
  lambda x,y,z: 60*z + (3*np.exp(-x*y)) + 10 * np.pi -3)
C:\Users\jessi\AppData\Local\Temp\ipykernel_14148\1074202749.py:16: RuntimeWarning: invalid value encountered in scalar subtract
  J[i,j] = ( f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2])  )/(2*h)
