In [44]:
import numpy as np

In [87]:
def multiplicacion(A,B):
    
    respuesta = None
  
    if len(B.shape) == 1:
        
        V = np.reshape(B,(3,1))
        
        
        filas_a = A.shape[0]
        columnas_a = A.shape[1]        
        
        columnas_V = len(V[0,:])
        
        filas_V = len(V[:,0])
        
        if columnas_a != filas_V:
            
            respuesta = "Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b"
            
        else:
            
            matrizr = np.zeros((filas_a,columnas_V))
            
            for fila in range(filas_a):
                
                f = A[fila,:]
                
                for columna in range(columnas_V):
                    
                    c = V[:,columna]
                    
                    valor = np.dot(f,c)
                    
                    matrizr[fila,columna] = valor
                    
                    respuesta = matrizr
        
    else: 
        
        filas_a = A.shape[0]
        columnas_a = A.shape[1]

        filas_b = B.shape[0]
        columnas_b = B.shape[1]
        
        if columnas_a != filas_b:
            
            respuesta = "Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b"
            
        else:
            
            matrizr = np.zeros((filas_a,columnas_b))
            
            for fila in range(filas_a):
                
                f = A[fila,:]
                
                for columna in range(columnas_b):
                    
                    c = B[:,columna]
                    
                    valor = np.dot(f,c)
                    
                    matrizr[fila,columna] = valor
                    
                    respuesta = matrizr
        
    return respuesta

Problema 1

In [103]:
A = np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B = np.array([5,-2,-3])

A[0,:]



array([ 5, -4, -2])

In [104]:
respuesta_1 = multiplicacion(A,B)

In [105]:
respuesta_1

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

Problema 2

In [90]:
C = np.array([[0,-1,-1,3],[5,-5,-2,2],[1,0,4,5]])
D = np.array([[0,-3],[-2,-1],[3,-3]])


respuesta_2 = multiplicacion(C,D)

In [91]:
respuesta_2

'Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b'

Problema 3

In [92]:
E = np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
F = np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])

respuesta_3 = multiplicacion(E,F)

In [93]:
respuesta_3

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

Demostración de la no conmutatividad de la multiplicación de matrices


In [97]:
G = np.array([[-2,2,3],[5,1,9],[3,6,7]])
H = np.array([[-7,9,5],[-1,3,2],[-6,4,2]])

respuesta_4 = multiplicacion(G,H)

respuesta_5 = multiplicacion(H,G)

In [98]:
respuesta_4

array([[ -6.,   0.,   0.],
       [-90.,  84.,  45.],
       [-69.,  73.,  41.]])

In [99]:
respuesta_5

array([[74., 25., 95.],
       [23., 13., 38.],
       [38.,  4., 32.]])