In [44]:
import numpy as np

In [75]:
def multiplicacion(A,B):
    
    respuesta = None
  
    if len(B.shape) == 1:
        
        V = np.reshape(B,(3,1))
        
        
        filas_a = A.shape[0]
        columnas_a = A.shape[1]        
        
        columnas_V = len(V[0,:])
        
        filas_V = len(V[:,0])
        
        if columnas_a != filas_V:
            
            respuesta = "Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b"
            
        else:
            
            matrizr = np.zeros((filas_a,columnas_V))
            
            for fila in range(filas_a):
                
                f = A[fila,:]
                
                for columna in range(columnas_V):
                    
                    c = V[:,columna]
                    
                    valor = np.dot(f,c)
                    
                    matrizr[fila,columna] = valor
                    
                    respuesta = matrizr
        
    else: 
        
        filas_a = A.shape[0]
        columnas_a = A.shape[1]

        filas_b = B.shape[0]
        columnas_b = B.shape[1]
        
        if columnas_a != filas_b:
            
            respuesta = "Las matrices no se pueden multiplicar porque el número de columnas de la matriz a no es el mismo número de filas de la matriz b"
            
        else:
            
            matrizr = np.zeros((filas_a,columnas_b))
            
            for fila in range(filas_a):
                
                f = A[fila,:]
                
                for columna in range(columnas_b):
                    
                    c = B[:,columna]
                    
                    valor = np.dot(f,c)
                    
                    matrizr[fila,columna] = valor
                    
                    respuesta = matrizr
        
    return respuesta

Problema 1

In [76]:
A = np.array([[5,-4,-1],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B = np.array([5,-2,3])

A[0,:]



array([ 5, -4, -1])

In [77]:
columnas_a

3

In [78]:
filas_b

3

In [79]:
n = len(A[:,0])

In [80]:
n

5

In [81]:
respuesta_1 = multiplicacion(A,B)

In [82]:
respuesta_1

array([[ 30.],
       [ 47.],
       [-12.],
       [-24.],
       [ 14.]])

Problema 2

In [64]:
C = np.array([[0,-1,-1,3],[5,-5,-2,2],[1,0,4,5]])
D = np.array([[0,-3],[-2,-1],[3,-3]])

filas_c = A.shape[0]
columnas_c = A.shape[1]

filas_d = B.shape[0]
columnas_d = B.shape[1]

respuesta_2 = multiplicacion(C,D,filas_c,columnas_c,filas_d,columnas_d)

IndexError: tuple index out of range

In [65]:
respuesta_2

NameError: name 'respuesta_2' is not defined

Problema 3

In [ ]:
E = np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
F = np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])

filas_e = E.shape[0]
columnas_e = E.shape[1]

filas_f = F.shape[0]
columnas_f = F.shape[1]

respuesta_3 = multiplicacion(E,F,filas_e,columnas_e,filas_f,columnas_f)

In [ ]:
respuesta_3

array([[ 12.,  27., -13.,  25.,   0.],
       [  2.,  51., -39., -46.,   0.],
       [ 27.,  -1., -19.,  16.,   0.],
       [ 13.,  25., -91.,  -1.,   0.]])

Demostración de la no conmutatividad de la multiplicación de matrices


In [ ]:
G = np.array([[-2,2,3],[5,1,9],[3,6,7]])
H = np.array([[-7,9,5],[-1,3,2],[-6,4,2]])

filas_g = G.shape[0]
columnas_g = G.shape[1]

filas_h = H.shape[0]
columnas_h = H.shape[1]

respuesta_4 = multiplicacion(G,H,filas_g,columnas_g,filas_h,columnas_h)

respuesta_5 = multiplicacion(H,G,filas_h,columnas_h,filas_g,columnas_g)

In [ ]:
respuesta_4

array([[ -6.,   0.,   0.],
       [-90.,  84.,  45.],
       [-69.,  73.,  41.]])

In [ ]:
respuesta_5

array([[74., 25., 95.],
       [23., 13., 38.],
       [38.,  4., 32.]])