In [255]:
import numpy as np

a. Usando minimos cuadrados matriciales.

In [256]:
A = np.array([[3,1,-1],[1,2,0],[0,1,2],[1,1,-1]])
b = np.array([-3,-3,8,9])

A

array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  1,  2],
       [ 1,  1, -1]])

In [257]:
A[:,0]

array([3, 1, 0, 1])

In [258]:
b

array([-3, -3,  8,  9])

In [259]:
AT = np.dot(A.T,A)
bT = np.dot(A.T,b)

xsol = np.linalg.solve(AT,bT)

In [260]:
xsol

array([-1.,  2.,  1.])

In [261]:
respuesta = np.dot(A,xsol)
respuesta

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  1.11022302e-16])

b.

In [262]:
base = []

In [263]:
u = A[:,0]
    
v_i = u / np.linalg.norm(u)

base.append(v_i)

In [264]:

for j in range(1,3):
    suma = 0
    u = A[:,j]
    for i in range(1,j+1):
        
        suma += ((np.dot(u,base[i-1]))/(np.dot(base[i-1],base[i-1]))*base[i-1])
 
    vector = A[:,j] - suma
       
    base.append(vector/np.linalg.norm(vector))
    
    

In [265]:
base

[array([0.90453403, 0.30151134, 0.        , 0.30151134]),
 array([-0.32961713,  0.75341057,  0.51796977,  0.2354408 ]),
 array([ 0.25633581, -0.26982716,  0.78249877, -0.49918025])]

In [270]:
vector = [0,0,0,0]

for i in range(3):
    
    constante = np.dot(b,base[i])
    
    vector += constante*base[i]
    


In [271]:
vector

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  5.55111512e-16])