In [2]:
import numpy as np

a. Usando minimos cuadrados matriciales.

In [23]:
A = np.array([[3,1,-1],[1,2,0],[0,1,2],[1,1,-1]])
b = np.array([-3,-3,8,9])

A

array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  1,  2],
       [ 1,  1, -1]])

In [24]:
b

array([-3, -3,  8,  9])

In [34]:
AT = np.dot(A.T,A)
bT = np.dot(A.T,b)

xsol = np.linalg.solve(AT,bT)

In [31]:
xsol

array([-1.,  2.,  1.])

In [41]:
respuesta = np.dot(A,xsol)
respuesta

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00,  1.11022302e-16])