In [27]:
import numpy as np

In [28]:
matriz_0 = np.array([[1.+0.j,0.,0.,0.],[0.,1.+0j,0.,0.],[0.,0.,-1+0.j,0.],[0.,0.,0.,-1.+0j]])

In [29]:
matriz_0

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [30]:
matriz_1 = np.array([[0.j,0.,0.,1.],[0.,0j,1.,0.],[0.,-1.,0.j,0.],[-1.,0.,0.,0j]])

In [31]:
matriz_1

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [32]:
matriz_2 = np.array([[0.,0.,0.,-1j],[0.,0.,1j,0.],[0.,1j,0.,0.],[-1j,0.,0.,0.]])

In [33]:
matriz_2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j,  0.+0.j,  0.+0.j],
       [-0.-1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [34]:
matriz_3 = np.array([[0.,0.,1.,0.],[0.,0.,0.,-1j],[-1j,0.,0.,0.],[0.,1j,0.,0.]])

In [35]:
matriz_3

array([[ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [-0.-1.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j,  0.+0.j,  0.+0.j]])

In [42]:
prueba = (np.dot(matriz_1,matriz_3))+(np.dot(matriz_3,matriz_1))

In [43]:
prueba

array([[ 0.+0.j, -1.+1.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+1.j,  0.+0.j]])